directory <- paste0(dirname(sys.frame(1)$ofile), '/../output/csv/')
c1 <- read.csv(file=paste0(directory, 'fetch_apple_search_ads_campaigns.csv'), sep=',', head=TRUE)
c2 <- read.csv(file=paste0(directory, 'fetch_facebook_campaigns.csv'), sep=',', head=TRUE)
c3 <- read.csv(file=paste0(directory, 'fetch_google_adwords_campaigns.csv'), sep=',', head=TRUE)
c <- merge(x=c1, y=c2, by.x='date', by.y='date_start', all=TRUE)
c <- merge(x=c, y=c3, by.x='date', by.y='day', all=TRUE)
c$spend <- with(c, localspend + spend + cost)
c <- c[c('date', 'spend')]
m <- read.csv(file=paste0(directory, 'fetch_appsflyer_data_locker.csv'), sep=',', head=TRUE)
d <- merge(x=c, y=m, by.x='date', by.y='event_date', all=TRUE)
a <- aggregate(d[c('spend', 'events', 'revenue')], by=list(date=d$date), FUN=sum)
a$cpe <- with(a, spend / events)
a$roas <- with(a, revenue / spend)
attach(mtcars)
par(mfrow=c(4,1))
plot(a$date, a$spend)
plot(a$date, a$events)
plot(a$date, a$cpe)
plot(a$date, a$roas)